Repository UKHomeOffice/hocs-info-service, pull requests merged in 2022-08, with the labels that each got.

#565 🐛 Fix the manual tag action
  .github/workflows/semver-data.yml
Labels: patch

#566 🐛 Fix the manual tag action
  .github/workflows/semver-data.yml
Labels: skip-release

#567 Update Readme to reflect java dependency change.
  README.md
Labels: patch

#573 HOCS-5363: mark case config as deprecated
  src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/dto/CaseConfigDto.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/model/CaseConfig.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/CaseTabRepository.java
Labels: patch

#571 renamed code occurrences of nothern irish and welsh assembly
  src/main/java/uk/gov/digital/ho/hocs/info/api/MemberService.java
  src/main/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerService.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/model/enums/House.java
  src/test/java/uk/gov/digital/ho/hocs/info/api/MemberServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerServicesTests.java
Labels: patch

#572 HOCS-5438: Support multi arch builds
  Dockerfile
Labels: minor

#578 HOCS-5279: deprecate reporting methods
  src/main/java/uk/gov/digital/ho/hocs/info/api/ExtractService.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaResource.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaService.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/SchemaRepository.java
Labels: minor

#579 HOCS-5279: deprecate custom export view methods
  src/main/java/uk/gov/digital/ho/hocs/info/api/ExportViewResource.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/ExportViewService.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ExportViewDto.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ExportViewFieldAdapterDto.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ExportViewFieldDto.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/model/ExportView.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/ExportViewRepository.java
Labels: minor

#580 HOCS-5489: add gro email domain
  kube/deploy.sh
Labels: patch

#586 Alter maxUnavailable to 0 based on prod experience
  kube/kd/deployment.yaml
Labels: patch
