Repository UKHomeOffice/hocs-info-service, pull requests merged in 2022-05, with the labels that each got.

#514 HOCS-5027: add dependabot GitHub Action update
  .github/dependabot.yml
Labels: skip-release

#512 HOCS-4409: Render tabs from DB
  src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/dto/CaseConfigDto.java
  src/main/java/uk/gov/digital/ho/hocs/info/api/dto/CaseTabDto.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/model/CaseConfig.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/model/CaseTab.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/CaseTabRepository.java
  src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/CaseTypeRepository.java
  src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeServiceTest.java
Labels: minor

#524 HOCS-5032: Update Secrets to match prod format
  kube/kd/deployment.yaml
Labels: patch

#528 HOCS-5032: Upgrade docker-compose and drone to use postgres 14
  .drone.yml
  docker-compose.yml
Labels: skip-release

#527 Chore: Upgrade drone build image version
  .drone.yml
Labels: skip-release

#529 Use latest main if tag for SHA not present
  .github/workflows/semver-data.yml
Labels: skip-release

#526 Add GitHub Action Slack failure notification
  .github/workflows/semver-data.yml
  .github/workflows/semver.yml
Labels: skip-release

#531 HOCS-4478: repoint to new column
  src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Field.java
  src/main/resources/db/postgresql/V1_55__4478_SwapIdForUuid.sql
  src/test/resources/beforeTest.sql
Labels: minor
